/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchwordRouteImport } from './routes/_app.watchword'
import { Route as AppTrashRouteImport } from './routes/_app.trash'
import { Route as AppShareRouteImport } from './routes/_app.share'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRecentRouteImport } from './routes/_app.recent'
import { Route as AppReceiveRouteImport } from './routes/_app.receive'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFavoritesRouteImport } from './routes/_app.favorites'
import { Route as AppDriveRouteImport } from './routes/_app.drive'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppDriveIndexRouteImport } from './routes/_app.drive.index'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as AppDriveFolderIdRouteImport } from './routes/_app.drive.$folderId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchwordRoute = AppWatchwordRouteImport.update({
  id: '/watchword',
  path: '/watchword',
  getParentRoute: () => AppRoute,
} as any)
const AppTrashRoute = AppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppRoute,
} as any)
const AppShareRoute = AppShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRecentRoute = AppRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiveRoute = AppReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveRoute = AppDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppDriveIndexRoute = AppDriveIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDriveRoute,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDriveFolderIdRoute = AppDriveFolderIdRouteImport.update({
  id: '/$folderId',
  path: '/$folderId',
  getParentRoute: () => AppDriveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AppAboutRoute
  '/drive': typeof AppDriveRouteWithChildren
  '/favorites': typeof AppFavoritesRoute
  '/home': typeof AppHomeRoute
  '/receive': typeof AppReceiveRoute
  '/recent': typeof AppRecentRoute
  '/search': typeof AppSearchRoute
  '/share': typeof AppShareRoute
  '/trash': typeof AppTrashRoute
  '/watchword': typeof AppWatchwordRoute
  '/drive/$folderId': typeof AppDriveFolderIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/drive/': typeof AppDriveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AppAboutRoute
  '/favorites': typeof AppFavoritesRoute
  '/home': typeof AppHomeRoute
  '/receive': typeof AppReceiveRoute
  '/recent': typeof AppRecentRoute
  '/search': typeof AppSearchRoute
  '/share': typeof AppShareRoute
  '/trash': typeof AppTrashRoute
  '/watchword': typeof AppWatchwordRoute
  '/drive/$folderId': typeof AppDriveFolderIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/drive': typeof AppDriveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/drive': typeof AppDriveRouteWithChildren
  '/_app/favorites': typeof AppFavoritesRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/receive': typeof AppReceiveRoute
  '/_app/recent': typeof AppRecentRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/share': typeof AppShareRoute
  '/_app/trash': typeof AppTrashRoute
  '/_app/watchword': typeof AppWatchwordRoute
  '/_app/drive/$folderId': typeof AppDriveFolderIdRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/_app/drive/': typeof AppDriveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/drive'
    | '/favorites'
    | '/home'
    | '/receive'
    | '/recent'
    | '/search'
    | '/share'
    | '/trash'
    | '/watchword'
    | '/drive/$folderId'
    | '/demo/sentry/testing'
    | '/drive/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/favorites'
    | '/home'
    | '/receive'
    | '/recent'
    | '/search'
    | '/share'
    | '/trash'
    | '/watchword'
    | '/drive/$folderId'
    | '/demo/sentry/testing'
    | '/drive'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/about'
    | '/_app/drive'
    | '/_app/favorites'
    | '/_app/home'
    | '/_app/receive'
    | '/_app/recent'
    | '/_app/search'
    | '/_app/share'
    | '/_app/trash'
    | '/_app/watchword'
    | '/_app/drive/$folderId'
    | '/demo/sentry/testing'
    | '/_app/drive/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watchword': {
      id: '/_app/watchword'
      path: '/watchword'
      fullPath: '/watchword'
      preLoaderRoute: typeof AppWatchwordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trash': {
      id: '/_app/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AppTrashRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/share': {
      id: '/_app/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AppShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recent': {
      id: '/_app/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof AppRecentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receive': {
      id: '/_app/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AppReceiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favorites': {
      id: '/_app/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drive': {
      id: '/_app/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AppDriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drive/': {
      id: '/_app/drive/'
      path: '/'
      fullPath: '/drive/'
      preLoaderRoute: typeof AppDriveIndexRouteImport
      parentRoute: typeof AppDriveRoute
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/drive/$folderId': {
      id: '/_app/drive/$folderId'
      path: '/$folderId'
      fullPath: '/drive/$folderId'
      preLoaderRoute: typeof AppDriveFolderIdRouteImport
      parentRoute: typeof AppDriveRoute
    }
  }
}

interface AppDriveRouteChildren {
  AppDriveFolderIdRoute: typeof AppDriveFolderIdRoute
  AppDriveIndexRoute: typeof AppDriveIndexRoute
}

const AppDriveRouteChildren: AppDriveRouteChildren = {
  AppDriveFolderIdRoute: AppDriveFolderIdRoute,
  AppDriveIndexRoute: AppDriveIndexRoute,
}

const AppDriveRouteWithChildren = AppDriveRoute._addFileChildren(
  AppDriveRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppDriveRoute: typeof AppDriveRouteWithChildren
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppReceiveRoute: typeof AppReceiveRoute
  AppRecentRoute: typeof AppRecentRoute
  AppSearchRoute: typeof AppSearchRoute
  AppShareRoute: typeof AppShareRoute
  AppTrashRoute: typeof AppTrashRoute
  AppWatchwordRoute: typeof AppWatchwordRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppDriveRoute: AppDriveRouteWithChildren,
  AppFavoritesRoute: AppFavoritesRoute,
  AppHomeRoute: AppHomeRoute,
  AppReceiveRoute: AppReceiveRoute,
  AppRecentRoute: AppRecentRoute,
  AppSearchRoute: AppSearchRoute,
  AppShareRoute: AppShareRoute,
  AppTrashRoute: AppTrashRoute,
  AppWatchwordRoute: AppWatchwordRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
