//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub filename: String,
    pub file_type: String,
    pub filesize: i64,
    pub filehash: String,
    pub url: String,
    pub folder_id: Option<Uuid>,
    pub author_id: Uuid,
    pub is_deleted: bool,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub ocr_text: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub caption: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub is_favorite: bool,
    #[sea_orm(has_many)]
    pub file_permissions: HasMany<super::file_permissions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "folder_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub folders: HasOne<super::folders::Entity>,
    #[sea_orm(has_many)]
    pub share_links: HasMany<super::share_links::Entity>,
    #[sea_orm(
        belongs_to,
        from = "author_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
