//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "folders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub folder_id: Option<Uuid>,
    pub owner_id: Uuid,
    pub is_deleted: bool,
    pub is_favorite: bool,
    pub total_size: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "folder_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub folders: HasOne<Entity>,
    #[sea_orm(
        belongs_to,
        from = "owner_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
