//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    pub avatar_url: Option<String>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub is_suspended: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(unique)]
    pub email: String,
    #[serde(skip_serializing)]
    pub password_hash: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub freeze_reason: Option<String>,
    #[sea_orm(has_many)]
    pub file_permissions: HasMany<super::file_permissions::Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
    #[sea_orm(has_many)]
    pub folders: HasMany<super::folders::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
